### ISSUE TITLE
blit_buffer method

### ISSUE THREAD

**Issue by themaire** [devbis/st7789py_mpy#2]
Hi. Thanks you so much for post this "slow" MicroPython module. Is enough quick for my modest project with on ESP32.

So, I can't understand to use the blit_buffer method. What is the image format for the buffer. Do you have a exemple or a link please?

Thanks you!!

**Comment by devbis** [comment]
blit_buffer just copies the content of the python's `buffer = bytearray()` to the display. 
The buffer should contain an array of pixels in the format, that depends on the screen's initial params.

By default, it uses 2-bytes 16bit color, so buffer must contain x * y * 2 pixels, that will be copied to the display's internal memory. It is useful to display images or high-resolution fonts.

```python
import machine

import st7789py as st7789
import arial48x as font

buf = bytearray(font.max_width() * font.height() * 2)

def iterate_bits(byte_list):
    for byte in byte_list:
        bits = [byte & (1 << num) > 0 for num in range(7, -1, -1)]
        for b in bits:
            yield b


def print_chr(chr_bitmap, dest_buffer, width, color, bgcolor=0):
    x = 0
    pixel_size = 2

    # font row is aligned to bytes, we have to skip the rest
    aligned_width = ((width >> 3) + (int(bool(width & 7)))) << 3
    correction = aligned_width - width

    pos = 0
    bit_iterator = iterate_bits(chr_bitmap)
    for b in bit_iterator:
        pix_color = color if b else bgcolor
        dest_buffer[pos] = (pix_color & 0xff00) >> 8
        dest_buffer[pos + 1] = pix_color & 0xff
        pos += pixel_size

        x += 1
        if x == width:
            x = 0
            for _ in range(correction):
                try:
                    next(bit_iterator)
                except StopIteration:
                    return


spi = machine.SPI(1, baudrate=40000000, polarity=1)
display = st7789.ST7789(
    spi, 240, 240,
    reset=machine.Pin(5, machine.Pin.OUT),
    dc=machine.Pin(2, machine.Pin.OUT),
)
display.init()


# get character bitmap and size
(bitmap, height, width) = font.get_ch('P')
# print char to the interbnal buffer
print_chr(bitmap, buf, width, color=0xffff, bgcolor=0x0)
# send buffer to the screen
display.blit_buffer(buf, 0, 0, width, height)
```

This example draws the letter "P" with the Arial font at (0, 0)

**Comment by themaire** [comment]
Hi thanks for your explain, interresting. For experiment, I did not found a similar arial48x module.

It's ok for the byte array to feed the blit_buffer method. So, I aleady played with a ssd1306 and used GIMP to create a perfect ppm file. Here I am lost to learn to produce a good file for the bytearray.

**Comment by themaire** [comment]
Ho my god I did it! Thanks for pushed me to my limits because I learned so mutch about dealing with bytearray and the generators in Python.
