### ISSUE TITLE
Display always green

### ISSUE THREAD

**Issue by ds2k5** [devbis/st7789py_mpy#3]
Hello,
tryed you example code on my ESP32D0WDQ6.

display.pixel(120, 120, st7789py.RED)

display.pixel(120, 120, st7789py.YELLOW)

But display always green.

It is a ST7789V not a ST7789 Display

http://www.lilygo.cn/claprod_view.aspx?TypeId=21&Id=1128&FId=t28:21:28

How to fix this ?
Thanks

**Comment by devbis** [comment]
Sorry, I can't help. I don't have the screen model that you have. 
There can be various reasons for that.

**Comment by ds2k5** [comment]
OK thanks
Send me a PM I have a idea

**Comment by devbis** [comment]
I added the default offsets for the 135x240 display. 
It may help with the positioning of pixels but I doubt it could solve your problem. Anyway, you can try
